### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by asriadirahim** [crdroidandroid/android_vendor_pixel-framework#3]
E AndroidRuntime: FATAL EXCEPTION: main
06-14 02:20:38.496  2327  2327 E AndroidRuntime: Process: com.android.systemui, PID: 2327
06-14 02:20:38.496  2327  2327 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Found interface com.android.systemui.statusbar.policy.HeadsUpManager, but class was expected (declaration of 'com.android.systemui.statusbar.policy.HeadsUpManager' appears in /system_ext/priv-app/SystemUIGoogle/SystemUIGoogle.apk!classes3.dex)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.actions.UnpinNotifications.updateHeadsUpListener(Unknown Source:0)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.actions.UnpinNotifications.<init>(Unknown Source:0)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.dagger.ElmyraModule.provideUnpinNotificationsElmyra(ElmyraModule.java:95)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.dagger.ElmyraModule_ProvideUnpinNotificationsElmyraFactory.provideUnpinNotificationsElmyra(ElmyraModule_ProvideUnpinNotificationsElmyraFactory.java:50)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.dagger.ElmyraModule_ProvideUnpinNotificationsElmyraFactory.get(ElmyraModule_ProvideUnpinNotificationsElmyraFactory.java:40)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.dagger.ElmyraModule_ProvideUnpinNotificationsElmyraFactory.get(ElmyraModule_ProvideUnpinNotificationsElmyraFactory.java:14)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.dagger.ElmyraModule_ProvideServiceConfigurationGoogleFactory.get(ElmyraModule_ProvideServiceConfigurationGoogleFactory.java:80)
06-14 02:20:38.496  2327  2327 E AndroidRuntime: 	at com.google.android.systemui.elmyra.dagger.ElmyraModule_ProvideServiceConfigurationGoogleFactory.get(ElmyraModule_ProvideServiceConfigurationGoogleFactory.java:22)

**Comment by gwolf2u** [comment]
please use issue_tracker
